apiVersion: v1
kind: Namespace
metadata: {name: cafe-boreal}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: {name: postgres-data, namespace: cafe-boreal}
spec:
  accessModes: [ReadWriteOnce]
  resources: {requests: {storage: 5Gi}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata: {name: postgres, namespace: cafe-boreal}
spec:
  serviceName: postgres
  replicas: 1
  selector: {matchLabels: {app: postgres}}
  template:
    metadata: {labels: {app: postgres}}
    spec:
      securityContext: {fsGroup: 999}
      containers:
      - name: postgres
        image: postgres:16-alpine
        envFrom: [{secretRef: {name: database-secret}}]
        ports: [{containerPort: 5432}]
        resources:
          requests: {cpu: 100m, memory: 256Mi}
          limits: {cpu: 500m, memory: 768Mi}
        readinessProbe: {exec: {command: [pg_isready, -U, cafeboreal]}, initialDelaySeconds: 5, periodSeconds: 5}
        livenessProbe: {exec: {command: [pg_isready, -U, cafeboreal]}, initialDelaySeconds: 180, periodSeconds: 10, failureThreshold: 6}
        volumeMounts: [{name: data, mountPath: /var/lib/postgresql/data}]
      volumes: [{name: data, persistentVolumeClaim: {claimName: postgres-data}}]
---
apiVersion: v1
kind: Service
metadata: {name: postgres, namespace: cafe-boreal}
spec:
  selector: {app: postgres}
  ports: [{port: 5432, targetPort: 5432}]
