const $=s=>document.querySelector(s), money=n=>new Intl.NumberFormat('es-CR',{style:'currency',currency:'CRC'}).format(n);
async function api(path,options={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...options});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
async function loadProducts(){const rows=await api('/api/catalog');$('#productGrid').innerHTML=rows.map(p=>`<article class="card"><span class="meta">Producto #${p.id}</span><h3>${p.nombre}</h3><p>${p.descripcion||'Sin descripción'}</p><p class="price">${money(p.precio)}</p><span class="pill" style="background:#e4eee8;color:#174d3b">Stock ${p.stock}</span></article>`).join('')}
async function loadCustomers(){const rows=await api('/api/customers');$('#customerList').innerHTML=rows.map(c=>`<div class="row"><strong>#${c.id} ${c.nombre}</strong><span>${c.email}</span><span>Identidad: ${c.numero_identidad}</span><span>Clave v${c.key_version}</span></div>`).join('')}
async function loadOrders(){const rows=await api('/api/orders');$('#orderList').innerHTML=rows.map(o=>`<div class="row"><strong>Pedido #${o.id}</strong><span>Cliente ${o.customer_id}</span><span>${o.items.length} línea(s)</span><span class="price">${money(o.total)}</span></div>`).join('')||'<p>No hay pedidos.</p>'}
async function loadLegacy(){const rows=await api('/legacy/inventory');$('#legacyList').innerHTML=rows.map(i=>`<div class="row"><strong>${i.sku}</strong><span>${i.nombre}</span><span>Stock legado</span><span>${i.stock}</span></div>`).join('')}
function formData(f){return Object.fromEntries(new FormData(f))}
productForm.onsubmit=async e=>{e.preventDefault();const x=formData(e.target);x.precio=+x.precio;x.stock=+x.stock;await api('/api/catalog',{method:'POST',body:JSON.stringify(x)});productDialog.close();e.target.reset();loadProducts()};
customerForm.onsubmit=async e=>{e.preventDefault();await api('/api/customers',{method:'POST',body:JSON.stringify(formData(e.target))});customerDialog.close();e.target.reset();loadCustomers()};
orderForm.onsubmit=async e=>{e.preventDefault();const x=formData(e.target);await api('/api/orders',{method:'POST',body:JSON.stringify({customer_id:+x.customer_id,items:[{product_id:+x.product_id,cantidad:+x.cantidad}]})});orderDialog.close();e.target.reset();loadOrders();loadProducts()};
Promise.all(['/api/catalog/healthz','/api/orders/healthz','/api/customers/healthz'].map(x=>api(x))).then(()=>{$('#status').textContent='● Servicios operativos';loadProducts();loadCustomers();loadOrders()}).catch(e=>{$('#status').textContent='● Requiere despliegue';console.error(e)});loadLegacy().catch(()=>{});
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');
